### ISSUE TITLE
I2C address should be determined from EEprom

### ISSUE THREAD

**Issue by gn36** [bigdisp/scoreboard-atmega8-i2c#1]
The i2c address should be determined by a setting variable in the eeprom so the program itself stays identical on all digits and only the address changes. 

---

Es gibt verschiedene Möglichkeiten, wie wir die Adressierung der verschiedenen Ziffern erledigen:
- Jede Ziffer bekommt ihre eigene Software (d.h. die Konstante mit der Adresse wird angepasst)
- Wir nutzen die externe Beschaltung eines der freien Ports um hiermit eine Adresse festzulegen.
- Wir schreiben die Adresse in den EEPROM des Atmega, so dass die Programmsoftware identisch bleibt.

Gibt es noch mehr Möglichkeiten? 

Ich würde aktuell die Variante mit dem EEPROM favorisieren. Eine eigene Software pro Mikrocontroller ist blöd zu warten, selbst wenn sich nur Konstanten ändern. Mit der externen Beschaltung verlieren wir große Teile eines Ports, den wir im Grunde für eine zweite Ziffer nutzen könnten wenn wir wollten. Die Kostenersparnis davon wäre zwar nicht riesig, weil die LED das teuerste sind, aber ca. eine Halbierung der Zahl der Platinen (7 -> 4 beim minimalen Modell, 15 -> 8 beim erweiterten) ist ja auch nicht schlecht. Der Verdrahtungsaufwand der einzelnen Platine steigt natürlich. Ansonsten hätte die externe Beschaltung natürlich den Vorteil, dass alle Microcontroller exakt identisch aufgebaut wären, wir die Dinger also einheitlich programmieren könnten, ohne anschließend noch den EEPROM befüllen zu müssen. 

@pluschris Meinung hierzu?

**Comment by pluschris** [comment]
Ja dann legen wir jetzt gleich mal die EEPROM-Variante fest. Aus den Gründen die du angeführt hast und selbst wenn wir bei einer Platine/Ziffer bleiben gilt:
- EEPROM schreiben ist schnell gemacht.
- EEPROM ist schneller geändert als fest gelötete Adresse an einem Port.
- EEPROM ist billiger als Mäuseklavier.

**Comment by gn36** [comment]
Ich mach das mal wieder auf, so dass ich weiß, dass  es in der Software noch fehlt ;)
